/* =========================================================
   DATA — voice-line manifest (LINES). Pure data, no game-state deps.
   Loaded BEFORE game.js (classic scripts share the top-level scope).
   {t: TTS text, r: rate, v: voice role}. New ids appear in the Voice
   Studio automatically. First slice of the no-build modular split.
========================================================= */
const LINES={
  /* letter sounds — override these with your own recordings for perfect phonics */
  snd_s:{t:"sss",r:.7}, snd_a:{t:"ahh",r:.7}, snd_t:{t:"tuh",r:.75},
  snd_p:{t:"puh",r:.75}, snd_i:{t:"ih",r:.7}, snd_n:{t:"nnn",r:.7},
  snd_m:{t:"mmm",r:.7}, snd_d:{t:"duh",r:.75}, snd_g:{t:"guh",r:.75},
  snd_o:{t:"o",r:.7}, snd_c:{t:"kuh",r:.75}, snd_k:{t:"kuh",r:.75},
  snd_e:{t:"eh",r:.7}, snd_u:{t:"uh",r:.7}, snd_r:{t:"rrr",r:.7},
  snd_h:{t:"hh",r:.7}, snd_b:{t:"buh",r:.75}, snd_f:{t:"fff",r:.7},
  snd_l:{t:"lll",r:.7}, snd_j:{t:"juh",r:.75}, snd_v:{t:"vvv",r:.7}, snd_w:{t:"wuh",r:.75},
  snd_x:{t:"ks",r:.75}, snd_y:{t:"yuh",r:.75}, snd_z:{t:"zzz",r:.7}, snd_q:{t:"kwuh",r:.75},
  like_s:{t:"Like sun!"}, like_a:{t:"Like apple!"}, like_t:{t:"Like tiger!"},
  like_p:{t:"Like pig!"}, like_i:{t:"Like insect!"}, like_n:{t:"Like nest!"},
  like_m:{t:"Like monkey!"}, like_d:{t:"Like dog!"}, like_g:{t:"Like goat!"},
  like_o:{t:"Like octopus!"}, like_c:{t:"Like cat!"}, like_k:{t:"Like kite!"},
  like_e:{t:"Like egg!"}, like_u:{t:"Like umbrella!"}, like_r:{t:"Like rocket!"},
  like_h:{t:"Like hat!"}, like_b:{t:"Like ball!"}, like_f:{t:"Like fish!"},
  like_l:{t:"Like lion!"}, like_j:{t:"Like jar!"}, like_v:{t:"Like van!"}, like_w:{t:"Like web!"},
  like_x:{t:"Like fox!"}, like_y:{t:"Like yo-yo!"}, like_z:{t:"Like zebra!"}, like_q:{t:"Like queen!"},
  intro_s:{t:"Mission! A Vexbot trapped the Letter Gem S! This is S. It says..."},
  intro_a:{t:"Mission! A Vexbot trapped the Letter Gem A! This is A. It says..."},
  intro_t:{t:"Mission! A Vexbot trapped the Letter Gem T! This is T. It says..."},
  intro_p:{t:"Mission! A Vexbot trapped the Letter Gem P! This is P. It says..."},
  intro_i:{t:"Mission! A Vexbot trapped the Letter Gem I! This is I. It says..."},
  intro_n:{t:"Mission! A Vexbot trapped the Letter Gem N! This is N. It says..."},
  intro_m:{t:"Mission! A Vexbot trapped the Letter Gem M! This is M. It says..."},
  intro_d:{t:"Mission! A Vexbot trapped the Letter Gem D! This is D. It says..."},
  intro_g:{t:"Mission! A Vexbot trapped the Letter Gem G! This is G. It says..."},
  intro_o:{t:"Mission! A Vexbot trapped the Letter Gem O! This is O. It says..."},
  intro_c:{t:"Mission! A Vexbot trapped the Letter Gem C! This is C. It says..."},
  intro_k:{t:"Mission! A Vexbot trapped the Letter Gem K! This is K. It says..."},
  intro_e:{t:"Mission! A Vexbot trapped the Letter Gem E! This is E. It says..."},
  intro_u:{t:"Mission! A Vexbot trapped the Letter Gem U! This is U. It says..."},
  intro_r:{t:"Mission! A Vexbot trapped the Letter Gem R! This is R. It says..."},
  intro_h:{t:"Mission! A Vexbot trapped the Letter Gem H! This is H. It says..."},
  intro_b:{t:"Mission! A Vexbot trapped the Letter Gem B! This is B. It says..."},
  intro_f:{t:"Mission! A Vexbot trapped the Letter Gem F! This is F. It says..."},
  intro_l:{t:"Mission! A Vexbot trapped the Letter Gem L! This is L. It says..."},
  intro_j:{t:"Mission! A Vexbot trapped the Letter Gem J! This is J. It says..."},
  intro_v:{t:"Mission! A Vexbot trapped the Letter Gem V! This is V. It says..."},
  intro_w:{t:"Mission! A Vexbot trapped the Letter Gem W! This is W. It says..."},
  intro_x:{t:"Mission! A Vexbot trapped the Letter Gem X! This is X. It says..."},
  intro_y:{t:"Mission! A Vexbot trapped the Letter Gem Y! This is Y. It says..."},
  intro_z:{t:"Mission! A Vexbot trapped the Letter Gem Z! This is Z. It says..."},
  intro_q:{t:"Mission! A Vexbot trapped the Letter Gem Q! This is Q. It says..."},
  /* --- ACT 2: digraph sounds, keywords, intros, words (one gem = one sound) --- */
  snd_sh:{t:"sh",r:.6}, snd_ch:{t:"ch",r:.7}, snd_th:{t:"th",r:.6}, snd_wh:{t:"wh",r:.6}, snd_ck:{t:"k",r:.75}, snd_ng:{t:"ng",r:.6},
  like_sh:{t:"Like ship!"}, like_ch:{t:"Like cheese!"}, like_th:{t:"Like thumb!"}, like_wh:{t:"Like whale!"}, like_ck:{t:"Like duck!"}, like_ng:{t:"Like ring!"},
  /* VOWEL TEAMS (ai/ee/oa) — one long-vowel sound; phonemes the parent can record (snd_ prefix) */
  snd_ai:{t:"ay",r:.7}, snd_ee:{t:"ee",r:.7}, snd_oa:{t:"oh",r:.7},
  intro_ai:{t:"This is the A-I team! Two vowels — the A does the talking and says its name.", v:"N"}, like_ai:{t:"Like rain!"},
  intro_ee:{t:"This is the E-E team! It says the long E — eee.", v:"N"}, like_ee:{t:"Like bee!"},
  intro_oa:{t:"This is the O-A team! The O does the talking and says its name.", v:"N"}, like_oa:{t:"Like boat!"},
  word_rain:{t:"rain!"}, word_train:{t:"train!"}, word_sail:{t:"sail!"}, word_feet:{t:"feet!"}, word_bee:{t:"bee!"}, word_tree:{t:"tree!"}, word_seed:{t:"seed!"},
  word_boat:{t:"boat!"}, word_coat:{t:"coat!"}, word_goat:{t:"goat!"}, word_soap:{t:"soap!"}, word_road:{t:"road!"}, word_leaf:{t:"leaf!"},
  intro_sh:{t:"New rune, brave knight! S and H join to make ONE sound... sh! Like ship.", v:"N"},
  intro_ch:{t:"New rune! C and H together say... ch! Like cheese.", v:"N"},
  intro_th:{t:"New rune! T and H together say... th! Like thumb.", v:"N"},
  intro_wh:{t:"New rune! W and H together say... wh! Like whale.", v:"N"},
  intro_ck:{t:"New rune! C and K at the end of a word say... k! Like duck.", v:"N"},
  intro_ng:{t:"New rune! N and G together say... ng! Like ring.", v:"N"},
  word_ship:{t:"ship!"}, word_chat:{t:"chat!"}, word_this:{t:"this!"}, word_duck:{t:"duck!"}, word_sock:{t:"sock!"},
  word_ring:{t:"ring!"}, word_king:{t:"king!"}, word_fish:{t:"fish!"}, word_chip:{t:"chip!"}, word_shop:{t:"shop!"},
  word_chin:{t:"chin!"}, word_bath:{t:"bath!"}, word_wing:{t:"wing!"}, word_dish:{t:"dish!"},
  /* Act-2 zone 2 — BLEND words */
  word_stop:{t:"stop!"}, word_frog:{t:"frog!"}, word_clap:{t:"clap!"}, word_swim:{t:"swim!"}, word_snap:{t:"snap!"},
  word_glad:{t:"glad!"}, word_plum:{t:"plum!"}, word_hand:{t:"hand!"}, word_jump:{t:"jump!"}, word_milk:{t:"milk!"},
  word_nest:{t:"nest!"}, word_sled:{t:"sled!"}, word_gift:{t:"gift!"}, word_trap:{t:"trap!"}, word_belt:{t:"belt!"},
  word_drum:{t:"drum!"}, word_flag:{t:"flag!"}, word_crab:{t:"crab!"}, word_star:{t:"star!"}, word_lamp:{t:"lamp!"},
  word_tent:{t:"tent!"}, word_mask:{t:"mask!"}, word_stomp:{t:"stomp!"}, word_blend:{t:"blend!"}, word_crust:{t:"crust!"}, word_drink:{t:"drink!"},
  blend_intro:{t:"To the Iron Forge, Sir Teddy! Here we BLEND sounds — two letters, side by side, said quickly together. Listen, then build!", v:"N"},
  /* Act-2 zone 3 — LONG VOWELS / Magic-E. Long-vowel sounds = the vowel's NAME. */
  snd_a_long:{t:"ay",r:.7}, snd_e_long:{t:"ee",r:.7}, snd_i_long:{t:"eye",r:.7}, snd_o_long:{t:"oh",r:.7}, snd_u_long:{t:"you",r:.7},
  magic_intro:{t:"A new spell, Sir Teddy — the MAGIC E! A short vowel says its little sound... but add a silent E at the end, and the vowel says its NAME!", v:"N"},
  magic_short:{t:"This word says..."},
  magic_cast:{t:"MAGIC E! The silent E flips the vowel — now it says its name!"},
  magic_done:{t:"Spell mastered! You can hear the long vowel sing. Noah the Red salutes you!", v:"N"},
  word_cape:{t:"cape!"}, word_tape:{t:"tape!"}, word_kit:{t:"kit!"}, word_kite:{t:"kite!"}, word_pine:{t:"pine!"},
  word_hope:{t:"hope!"}, word_not:{t:"not!"}, word_note:{t:"note!"}, word_cub:{t:"cub!"}, word_cube:{t:"cube!"},
  word_tub:{t:"tub!"}, word_tube:{t:"tube!"}, word_cake:{t:"cake!"}, word_time:{t:"time!"}, word_home:{t:"home!"},
  word_rope:{t:"rope!"}, word_bike:{t:"bike!"}, word_gate:{t:"gate!"}, word_nose:{t:"nose!"}, word_rose:{t:"rose!"}, word_cute:{t:"cute!"},
  /* Act-2 zone 7 — R-CONTROLLED ("Bossy R"). er/ir/ur all say /ər/; snd_ir/snd_ur reuse the snd_er clip
     (PHON_ALIAS in audio.js) and read the SAME /ər/ in TTS so the child hears one sound, three spellings. */
  snd_ar:{t:"ar",r:.7}, snd_or:{t:"or",r:.7}, snd_er:{t:"er",r:.7}, snd_ir:{t:"er",r:.7}, snd_ur:{t:"er",r:.7},
  intro_ar:{t:"A new sound, brave knight — Bossy R! When R stands behind A, it gets bossy: the A can't say its name. A-R says... ar! Like a pirate — arrr!", v:"N"},
  intro_or:{t:"Bossy R again! O and R together say... or! Like corn.", v:"N"},
  intro_er:{t:"Here is the /er/ sound. E and R together say... er! Like fern.", v:"N"},
  intro_ir:{t:"A surprise, Sir Teddy — I and R ALSO say... er! Same sound, new spelling. Like bird.", v:"N"},
  intro_ur:{t:"And U and R say... er, too! Three spellings, one bossy sound. Like surf.", v:"N"},
  like_ar:{t:"Like car!"}, like_or:{t:"Like corn!"}, like_er:{t:"Like fern!"}, like_ir:{t:"Like bird!"}, like_ur:{t:"Like surf!"},
  word_car:{t:"car!"}, word_fork:{t:"fork!"}, word_corn:{t:"corn!"}, word_her:{t:"her!"}, word_bird:{t:"bird!"},
  word_fur:{t:"fur!"}, word_girl:{t:"girl!"}, word_surf:{t:"surf!"}, word_turn:{t:"turn!"}, word_church:{t:"church!"}, word_fern:{t:"fern!"},
  /* Act-2 zone 8 — BIG WORDS (multisyllabic + affixes). The chop/peel procedure, not syllable names. */
  syll_intro:{t:"A GIANT word, Sir Teddy! Too big to read at once — so we CHOP it into chunks. Tap each part, read it, then push them together!", v:"N"},
  affix_intro:{t:"Some words wear an ending or a beginning, like armor! Peel it off, read the little word inside, then put it back. Tap CHOP!", v:"N"},
  syll_look:{t:"A big word! Listen, then chop it."},
  syll_and:{t:"...and..."}, syll_push:{t:"Push them together..."},
  syll_done:{t:"You read a GIANT word! A true Word Knight. Noah the Red is amazed!", v:"N"},
  word_sunset:{t:"sunset!"}, word_cobweb:{t:"cobweb!"}, word_hotdog:{t:"hotdog!"}, word_laptop:{t:"laptop!"}, word_backpack:{t:"backpack!"},
  word_rabbit:{t:"rabbit!"}, word_napkin:{t:"napkin!"}, word_magnet:{t:"magnet!"}, word_basket:{t:"basket!"}, word_helmet:{t:"helmet!"},
  word_tiger:{t:"tiger!"}, word_robot:{t:"robot!"}, word_lemon:{t:"lemon!"}, word_robin:{t:"robin!"},
  word_jumps:{t:"jumps!"}, word_jumping:{t:"jumping!"}, word_helping:{t:"helping!"}, word_kicking:{t:"kicking!"}, word_jumped:{t:"jumped!"},
  word_planted:{t:"planted!"}, word_rained:{t:"rained!"}, word_faster:{t:"faster!"}, word_fastest:{t:"fastest!"}, word_longer:{t:"longer!"},
  word_jumper:{t:"jumper!"}, word_undo:{t:"undo!"}, word_redo:{t:"redo!"}, word_unlock:{t:"unlock!"}, word_unzip:{t:"unzip!"}, word_distrust:{t:"distrust!"},
  word_tent:{t:"tent!"},
  /* Noah the Red — Act-2 mentor intro */
  noah1:{t:"Greetings, young hero. I am Noah the Red, wizard of the old realm. The Vixen has dragged your friends here, to the age of knights and dragons.", v:"N"},
  noah2:{t:"Your gem-powers are gone — but together we will earn new magic: RUNES. Two letters that join to make ONE sound. Master them, and the dragons cannot stand against you.", v:"N"},
  noah3:{t:"Welcome to Stonekeep Village, Sir Teddy. Your first runes await. Onward!", v:"N"},
  act2_win:{t:"A dragon falls! Your runes grow stronger, Sir Teddy. Noah the Red is proud.", v:"N"},
  drag_intro:{t:"A dragon guards the way, Sir Teddy! Bring it down — tap the gem that says...", v:"N"},
  drag_flee:{t:"The dragon falls back in defeat! Onward, brave knight!", v:"N"},
  win_grow2:{t:"Rune mastered! Your power grows, Sir Teddy — you'll be a SOLDIER in no time!", v:"N"},
  word_at:{t:"at!"}, word_sat:{t:"sat!"}, word_tap:{t:"tap!"}, word_pin:{t:"pin!"}, word_nap:{t:"nap!"},
  word_dad:{t:"dad!"}, word_mad:{t:"mad!"}, word_dig:{t:"dig!"},
  word_cat:{t:"cat!"}, word_dog:{t:"dog!"}, word_mom:{t:"mom!"}, word_kid:{t:"kid!"},
  word_red:{t:"red!"}, word_run:{t:"run!"}, word_rug:{t:"rug!"}, word_rub:{t:"rub!"},
  word_fun:{t:"fun!"}, word_hen:{t:"hen!"}, word_bed:{t:"bed!"}, word_bug:{t:"bug!"},
  word_sun:{t:"sun!"}, word_pig:{t:"pig!"}, word_hat:{t:"hat!"}, word_cup:{t:"cup!"}, word_bus:{t:"bus!"},
  word_bag:{t:"bag!"}, word_cap:{t:"cap!"}, word_pan:{t:"pan!"}, word_nut:{t:"nut!"}, word_fan:{t:"fan!"},
  word_mug:{t:"mug!"}, word_pot:{t:"pot!"}, word_hug:{t:"hug!"}, word_net:{t:"net!"}, word_bun:{t:"bun!"},
  word_let:{t:"let!"}, word_jam:{t:"jam!"}, word_van:{t:"van!"}, word_box:{t:"box!"}, word_fox:{t:"fox!"}, word_zip:{t:"zip!"}, word_wax:{t:"wax!"},
  word_hop:{t:"hop!"}, word_wet:{t:"wet!"},
  cloze_intro:{t:"READING DOJO! Read the whole sentence, then tap the word that fits the blank!"},
  cloze_prompt:{t:"Which word fits? Read it and tap!"},
  scram_intro:{t:"Sentence building! Listen to the sentence, then tap the words in the right order!"},
  scram_prompt:{t:"Build the sentence! Tap the words in order."},
  dojo_yes:{t:"Perfect reading, Super Teddy!"},
  gear_fluency:{t:"The FLUENCY BADGE! You read like a real reader now!"},
  m4_letters:{t:"You rescued ALL the Letter Gems! Every letter in Star Force City is FREE! Now... the road to reading, and to Lord Vex's Fortress!"},
  read_intro:{t:"READING RALLY! Now YOU read the words, hero. Sound them out, then tap the picture it means!"},
  read_prompt:{t:"Read the word... then tap what it means!"},
  read_yes:{t:"You READ it! Awesome!"},
  rally_champ:{t:"You are a READING CHAMPION, Super Teddy! You can read real words now!"},
  gear_crown:{t:"The READING CROWN! Only true readers can wear it!"},
  gear_alphabet:{t:"The ALPHABET STAR! All 26 Letter Gems, rescued by you!"},
  sw_I:{t:"I"}, sw_a:{t:"a"}, sw_the:{t:"the"}, sw_to:{t:"to"}, sw_and:{t:"and"},
  sw_is:{t:"is"}, sw_you:{t:"you"}, sw_said:{t:"said"},
  spell_intro:{t:"HEART WORDS! Most of each word you CAN sound out — only the heart letter is tricky, so we just remember that one bit."},
  spell_new:{t:"Let's map the sounds. This word says..."},
  spell_build:{t:"Build the word you hear — sound by sound!"},
  spell_heart:{t:"Heart letter! This one's tricky — we just remember it."},
  spell_prompt:{t:"Cast the Instant Spell that says..."},
  spell_yes:{t:"Spell built! You mapped the sounds!"},
  spell_done:{t:"You are a MASTER SPELL CASTER, Super Teddy! Heart words: mastered!"},
  gear_tome:{t:"The SPELL TOME! It holds every heart word you know!"},
  word_ran:{t:"ran!"}, word_hot:{t:"hot!"}, word_big:{t:"big!"}, word_can:{t:"can!"}, word_had:{t:"had!"},
  sent_intro:{t:"THE STORY GATE! This is real reading, hero. Tap each word to read it, then tap the picture the sentence tells about!"},
  sent_prompt:{t:"Read the whole sentence... then tap the picture it tells about!"},
  sent_yes:{t:"YES! You READ a whole sentence, Super Teddy!"},
  sent_champ:{t:"You did it! You can READ, Super Teddy! Real sentences! The Story Gate is OPEN — Lord Vex's Fortress is next!"},
  gear_storykey:{t:"The STORY KEY! It unlocks every story in Star Force City!"},
  /* Beat-1 cold-open hook (STORY.md §G, APPROVED parent 2026-06-16): wonder/threat fast, READING is the
     superpower (panel4 = reading the gem brings the city back), mom-&-dad-chose-you, end on "you're ready". */
  panel1:{t:"Look up there — Star Force City, the brightest city in the whole galaxy, powered by glowing Letter Gems."},
  panel2:{t:"Then the lights went out. Lord Vex and his Vexbots stole the gems and smashed every word to pieces — now no one can read. Not a single sign. Not one bedtime story."},
  panel3:{t:"The city needs a hero to bring the words back. Your mom and dad searched everywhere — and they chose YOU."},
  panel4:{t:"Put on your Gem Lenses. When you READ a gem, it lights up — and the city comes back to life, word by word."},
  panel5:{t:"You're Super Teddy now. Rescue the gems, rebuild the words, save the city. Ready, hero?"},
  welcome:{t:"Welcome back, Super Teddy!"},
  locked_tip:{t:"Not yet, hero! Finish the missions on the path first — then this one unlocks."},
  pick:{t:"Pick your mission, Super Teddy!"},
  scan_intro:{t:"Lens calibration! Let's charge your Gem Lenses. There are no wrong answers. Every tap makes them stronger!"},
  scan_prompt:{t:"Tap the gem that says..."},
  scan_done:{t:"Lenses fully charged! Time for your first mission, hero!"},
  trace_prompt:{t:"Trace the gem to cut it free! Follow the glowing stars with your finger."},
  freed:{t:"You cut the gem free!"},
  find_prompt:{t:"Find the gem that says..."},
  yes:{t:"Yes!"},
  almost:{t:"Almost! Listen again..."},
  boss_intro:{t:"A VEXBOT is attacking! Blast it! Tap the gem that says..."},
  hit_again:{t:"Direct hit! Again!"},
  dodge:{t:"He dodged! Listen..."},
  flee:{t:"SYSTEM FAILURE! VEXBOT RETREATING!", v:"C"},
  youdidit:{t:"You did it, Super Teddy!"},
  /* ---- villain BATTLE taunts (intro monologue) + DEFEAT lines ("I'll get you next time") ---- */
  boss_taunt:{t:"You again, Super Teddy? Hand over those Letter Gems and nobody gets zapped!", v:"C"},
  boss_flee:{t:"This isn't over, hero! I'll be back for those gems!", v:"C"},
  vex_taunt:{t:"So... you reached my fortress. Foolish child. You will NEVER read your way past LORD VEX!", v:"C"},
  vex_defeat:{t:"Impossible! Beaten by a child who learned to READ?! I'll get you next time, Super Teddy!", v:"C"},
  vixen_taunt:{t:"Welcome to my Dragon Keep, little knight. Miss Kendall belongs to ME now. Turn back while you can!", v:"V"},
  vixen_defeat:{t:"NO! My beautiful dragon! You have NOT seen the last of me, Sir Teddy. I'll get you next time!", v:"V"},
  /* boss-trophy cage quips (tap a caged, shrunken villain on the Hero Base shelf) */
  cage_captain:{t:"Bested by a little reader?! The Vexbots will NEVER let me live this down...", v:"C"},
  cage_vex:{t:"I cannot BELIEVE I was beaten by a child who learned to READ. Impossible!", v:"C"},
  cage_dragon:{t:"Grrr... shrunk down and caged — all because you sounded out my runes!", v:"V"},
  cage_vixen:{t:"Darling, this cage clashes with my outfit. You read your way past my dragon... well played, little knight.", v:"V"},
  patrol_intro:{t:"Rooftop patrol! Letter Gems are hiding all over the city. Find them, hero!"},
  mastery_review:{t:"So close, hero! A few Letter Gems need more power before this rescue. Quick patrol to lock them in!"},
  cue_b:{t:"Watch out, hero! b and d are mirror twins. b has its round belly in FRONT, after the tall line. Listen: buh — like ball!"},
  cue_d:{t:"Careful! d and b are mirror twins. d has its round belly FIRST, before the tall line. Listen: duh — like dog!"},
  cue_p:{t:"Watch out! p and q are mirror twins. p has its round belly in FRONT. Listen: puh — like pig!"},
  cue_q:{t:"Careful! q and p are mirror twins. q has its round belly FIRST, with a tail. Listen: kwuh — like queen!"},
  cue_n:{t:"Careful! n and m are alike. n has ONE bump. Listen: nnn — like nest!"},
  cue_m:{t:"Watch out! m and n are alike. m has TWO bumps. Listen: mmm — like monkey!"},
  cue_u:{t:"Careful! u and n are flips. u is a cup, open at the TOP. Listen: uh — like umbrella!"},
  cue_w:{t:"Watch out! w and m are flips. w points UP like two valleys. Listen: wuh — like web!"},
  daily_goal:{t:"Daily training complete! You trained like a true champion today, Super Teddy!"},
  forge_intro1:{t:"The WORD FORGE is open!"},
  forge_intro2:{t:"Gems together make WORDS. And words forge the mightiest weapons!"},
  forge_build:{t:"Build the word! Listen..."},
  forge_next:{t:"Next sound..."},
  forge_listen:{t:"Listen for the next sound..."},
  blast:{t:"BLAST!"},
  forge_win1:{t:"The Vexbot is DESTROYED!"},
  forge_win2:{t:"You READ words, Super Teddy! You are a true hero!"},
  win_grow:{t:"Gem rescued! Your power grows, Super Teddy! Look at those muscles!"},
  win_gear:{t:"You earned new gear!"},
  gear_belt:{t:"The Power Belt!"}, gear_boots:{t:"Rocket Boots!"}, gear_shield:{t:"The GEM SHIELD! Forged from power words!"}, gear_gauntlet:{t:"The GEM GAUNTLET! Now your word power is unstoppable!"},
  m3_done:{t:"You crushed the Vex Captain and conquered Thunder Ridge! Lord Vex's Fortress is just ahead, Super Teddy..."},
  gear_hammer:{t:"The WORD HAMMER! Forged from your first words!"}, gear_sword:{t:"The GEM SWORD! A true hero's blade!"}, base1:{t:"Welcome to your Hero Base, Super Teddy! Gear up and look strong!"},
  train_intro:{t:"Training Room! Build and read words to earn coins, Super Teddy. Practice makes you POWERFUL!"},
  train_build:{t:"Build the word you hear!"},
  train_read:{t:"Read the word, then tap what it means!"},
  train_yes:{t:"Coin earned!"},
  train_none:{t:"Learn a few letters on the missions first, then come back to train!"},
  scroll_intro:{t:"A Spell Scroll! First listen as I read it. Then YOU read it out loud, hero!"},
  scroll_listen:{t:"Listen, and watch the words light up."},
  scroll_read:{t:"Now YOU read it! Say each word and tap it, in order."},
  scroll_again:{t:"Tap the glowing word next!"},
  scroll_done:{t:"You read the whole scroll! Your reading power is growing!"},
  scroll_best:{t:"A new personal best! You read it like a true hero!"},
  warmup_intro:{t:"Sound Warm-Up! Let's get your super ears ready, hero."},
  warmup_blend:{t:"Listen to the sounds… what word is it? Tap the picture!"},
  warmup_seg:{t:"How many sounds do you hear? Tap the dice with that many dots!"},
  warmup_iso:{t:"What sound does it start with? Tap the gem!"},
  warmup_done:{t:"Ears warmed up! Now you're ready to train, Super Teddy!"},
  vault_intro:{t:"Time to recharge your gems, Super Teddy! Let's power up the ones you already know!"},
  vault_build:{t:"Recharge it — build the word you hear!"},
  vault_full:{t:"Your gems are fully charged! Come back tomorrow, hero!"},
  vault_done:{t:"All charged up! Your gems are glowing strong!"},
  vault_nudge:{t:"Psst — some of your gems are ready for a recharge! Tap the Vault when you want to power them up."},
  rankup:{t:"WHOA — you LEVELED UP, Super Teddy! Your power bar is full — you're even stronger now!"},
  shop_need:{t:"Not enough coins yet — train a little more, hero!"},
  finale1:{t:"Incoming message! ... Super Teddy! It's Amelia!", v:"B"},
  finale2:{t:"Lord Vex trapped me in the Heart Tower! Come rescue me in your next adventure!", v:"B"},
  finale3:{t:"To be continued, hero..."},
  fort_intro:{t:"THIS IS IT, Super Teddy! Lord Vex's Fortress! Leighton is locked inside. Use EVERYTHING you've learned — bring him down!"},
  fort_t1:{t:"FOOLISH HERO! My gem shield is UNBREAKABLE!", v:"C"},
  fort_t2:{t:"You cannot read my word-locks! NOBODY can!", v:"C"},
  fort_t3:{t:"Impossible! How do you know these spells?!", v:"C"},
  fort_t4:{t:"NO! Not the sentences! My power is FADING!", v:"C"},
  fort_p1:{t:"PHASE ONE — blast the GEM SHIELD! Tap the gem that makes the sound…"},
  fort_p2:{t:"PHASE TWO — smash the WORD-LOCKS! Read each word, tap what it means!"},
  fort_p3:{t:"PHASE THREE — cast your INSTANT SPELLS! Tap the word you hear!"},
  fort_p4:{t:"FINAL PHASE — READ to free Leighton! Read each sentence and answer it!"},
  fort_hit:{t:"DIRECT HIT!"},
  fort_win1:{t:"VEX'S ARMOR SHATTERS! SYSTEM FAILURE!", v:"C"},
  leighton1:{t:"You did it, Super Teddy! You READ your way to victory! Lord Vex is defeated!", v:"L"},
  leighton2:{t:"Super Teddy! You found me! I always knew you could read! You're my hero!", v:"L"},
  leighton3:{t:"LEIGHTON is FREE! Star Force City is SAVED! The main story is complete — you are a true READER and a true HERO!", v:"L"},
  interlude1:{t:"Wait, Super Teddy — an urgent message is coming in! It's your Mom and Dad!"},
  interlude2:{t:"Hero, we are SO proud of you. But there's no time to rest. A cunning new villain has appeared — and she has kidnapped Miss Kendall... and your friends JJ, Nora, and Cal!", v:"P"},
  interlude3:{t:"Hello, little hero. Such a shame to spoil your party. I'm whisking your precious friends far, far away — to a time long, long ago. Do try to catch up... if you can. Ta-ta!", v:"V"},
  interlude4:{t:"She slipped through a shimmering time portal — to the age of KNIGHTS and DRAGONS! A mighty wizard named Noah the Red is already there, waiting to help you, hero."},
  interlude_knight:{t:"You leap into the portal! In a swirl of light your gems and gear are gone... and you rise again as SUPER TEDDY THE SQUIRE! Train hard, brave reader, and you will earn your knighthood."},
  interlude5:{t:"And so a brave new quest begins. Onward, Sir Teddy — the Magic Kingdom awaits!"},
  /* ===== ACT-2 FINALE — Dragon Keep / rescue Miss Kendall ===== */
  f2_intro:{t:"THE DRAGON KEEP, Sir Teddy! The Vixen has Miss Kendall locked in the highest tower, guarded by her mightiest dragon. Use your RUNES, your BLENDS, and your MAGIC-E — bring it down!", v:"N"},
  f2_p1:{t:"Break the dragon ward! Tap the gem that makes the sound…"},
  f2_p2:{t:"Shatter the rune-locks! Read the word, then tap what it means!"},
  f2_p3:{t:"Cast your spells! Build the word you hear — sound by sound!"},
  f2_p4:{t:"FINAL STAND — read to free Miss Kendall! Read the word and tap what it means!"},
  f2_t1:{t:"You shall not pass, little knight!", v:"V"},
  f2_t2:{t:"My runes will hold forever!", v:"V"},
  f2_t3:{t:"Magic? You call THAT magic?", v:"V"},
  f2_t4:{t:"No! My dragon — it falls!", v:"V"},
  f2_win:{t:"The dragon is defeated! The Vixen flees in a swirl of smoke!"},
  kendall1:{t:"You did it, Sir Teddy! You READ your way through the whole Dragon Keep!", v:"K"},
  kendall2:{t:"Teddy! My brave knight — you came for me! I always knew you would learn to read. Thank you, hero!", v:"K"},
  kendall3:{t:"MISS KENDALL is FREE! The Magic Kingdom is safe, and you are a TRUE READER and a TRUE KNIGHT. What a champion!", v:"K"},
  free_tank:{t:"CAGE DESTROYED! You freed Archie! Archie has joined the Hero League... and he is ready to SMASH!"},
  free_flip:{t:"CAGE DESTROYED! You freed Ellie! Ellie has joined the league... backflips, cartwheels, and mid-air gem grabs!"},
  free_sunny:{t:"CAGE DESTROYED! You freed William! William has joined the league... and things are about to get silly!"},
  free_heart1:{t:"TOWER UNLOCKED! You read your way to the top of Heart Tower!"},
  free_heart2:{t:"Super Teddy! You saved me! I KNEW you could read those words! Amelia is on the team, little hero!", v:"B"},
  m2_done:{t:"AMELIA has joined the Hero League! Lord Vex is furious... and Star Force City shines brighter than ever!"},
  /* ACT 2 friend rescues (spread across zones, parent 2026-06-16): the dragon falls + the friend is freed.
     Best in the real kids' voices via the Studio (roles J/R/X). */
  jj_freed:{t:"The Iron Wyrm is down — and you freed ME! Whoa, that was AWESOME reading! JJ is on the team!", v:"J"},
  cal_freed:{t:"You beat the dragon AND busted me out? Ha! Knew you'd do it. Cal has joined the league!", v:"X"},
  nora_freed:{t:"You read your way right to me — thank you, Super Teddy! Nora is so proud to join your team!", v:"R"},
  heart_cheer1:{t:"Amazing reading, Super Teddy!", v:"B"},
  heart_cheer2:{t:"That's my little brother, everyone!", v:"B"},
  heart_cheer3:{t:"Amelia is SO proud of you!", v:"B"},
  /* hero-card signature lines — spoken when you tap a friend's card in the Base */
  card_tank:{t:"Hey Teddy! Need some big muscles? I've got you, buddy! And WOW — you are getting SO good at reading!", v:"T"},
  card_flip:{t:"Hi Teddy! Did you see that flip? Keep reading like a champ — you've totally got this!", v:"F"},
  card_sunny:{t:"Teddy! Up high! Your reading is out of this WORLD, little buddy! Ha ha!", v:"W"},
  card_heart:{t:"I'm so proud of you, Teddy. You're reading so beautifully — keep it up, sweetheart!", v:"B"},
  card_leighton:{t:"You saved me, Super Teddy! And now you can READ — I always knew you could do it!", v:"L"},
  card_kendall:{t:"Look at you reading, Teddy — my brave knight and my star student. I'm so proud of you!", v:"K"},
  cheer_archie1:{t:"BOOM! Smash that Vexbot, Super Teddy! Archie's got your back!", v:"T"},
  cheer_archie2:{t:"So strong, Super Teddy! That's how Archie does it! Hit it again!", v:"T"},
  cheer_ellie1:{t:"Beautiful, Super Teddy! Ellie says you stuck the landing!", v:"F"},
  cheer_ellie2:{t:"Woo! Super neat tracing! Ellie's doing a cartwheel for you!", v:"F"},
  cheer_will1:{t:"Wheee! William found it! Wait... YOU found it! Hooray!", v:"W"},
  cheer_will2:{t:"Sparkles everywhere! Awesome finding, Super Teddy! Says William!", v:"W"},
  /* TRAINING-ROOM INTERRUPTS (between-rep pop-ins; TRAINING-INTERRUPTS.md, parent-approved 2026-06-16).
     5 tellers x 20: Archie(T)+Nora(R) cheer; William(W), JJ(J), Cal(X) joke. Best in the real kids' voices. */
  train_arch1:{t:"YES! Keep it up, Teddy — you're getting STRONG!", v:"T"},
  train_arch2:{t:"Whoa, look at you read! Don't stop now, champ.", v:"T"},
  train_arch3:{t:"Every word makes your muscles bigger. Go go go!", v:"T"},
  train_arch4:{t:"You've got this, hero. One more!", v:"T"},
  train_arch5:{t:"Boom! That's my buddy. Keep crushing it.", v:"T"},
  train_arch6:{t:"Look at those reading muscles GROW!", v:"T"},
  train_arch7:{t:"You're on fire, Teddy! Keep blasting through!", v:"T"},
  train_arch8:{t:"That's how a hero trains. Awesome work!", v:"T"},
  train_arch9:{t:"High five! You get faster every single time.", v:"T"},
  train_arch10:{t:"Don't quit now — you're almost a super-reader!", v:"T"},
  train_arch11:{t:"Strong body, strong brain. You've got both, buddy!", v:"T"},
  train_arch12:{t:"I knew you could do it. Keep going, champ!", v:"T"},
  train_arch13:{t:"Every rep makes you tougher. Let's GO!", v:"T"},
  train_arch14:{t:"You make it look easy, hero. One more rep!", v:"T"},
  train_arch15:{t:"That was a big one — and you powered right through it!", v:"T"},
  train_arch16:{t:"Reading like a champion. I'm so proud of you.", v:"T"},
  train_arch17:{t:"Keep that streak alive, Teddy. You're unstoppable!", v:"T"},
  train_arch18:{t:"Pow! Another word down. You're a machine!", v:"T"},
  train_arch19:{t:"Your power bar is climbing. Don't stop now!", v:"T"},
  train_arch20:{t:"That's my hero — strong, brave, and SMART.", v:"T"},
  train_will1:{t:"What do you call a sleeping dinosaur? A dino-SNORE!", v:"W"},
  train_will2:{t:"Why did the cookie go to the doctor? It felt CRUMBY!", v:"W"},
  train_will3:{t:"What's brown and sticky? A stick!", v:"W"},
  train_will4:{t:"Why can't your nose be twelve inches long? Because then it'd be a FOOT!", v:"W"},
  train_will5:{t:"What do you call a fish with no eyes? A fshhh!", v:"W"},
  train_will6:{t:"What did one toilet say to the other? You look FLUSHED!", v:"W"},
  train_will7:{t:"Why don't eggs tell jokes? They'd CRACK each other up!", v:"W"},
  train_will8:{t:"What's invisible and smells like carrots? Bunny TOOTS!", v:"W"},
  train_will9:{t:"What do you call a cow with no legs? Ground beef!", v:"W"},
  train_will10:{t:"Why was the broom late? It over-SWEPT!", v:"W"},
  train_will11:{t:"What do you call a dinosaur toot? A blast from the PAST!", v:"W"},
  train_will12:{t:"What do you call a bear with no teeth? A GUMMY bear!", v:"W"},
  train_will13:{t:"Why was six scared of seven? Because seven ATE nine!", v:"W"},
  train_will14:{t:"What does a cloud wear under its shorts? THUNDERWEAR!", v:"W"},
  train_will15:{t:"Knock knock! Who's there? Boo. Boo who? Aw, don't cry — it's just me!", v:"W"},
  train_will16:{t:"What's a monster's favorite snack? I-SCREAM!", v:"W"},
  train_will17:{t:"Why did the teddy bear say no to dessert? He was STUFFED!", v:"W"},
  train_will18:{t:"What do you call a pig that does karate? A pork CHOP!", v:"W"},
  train_will19:{t:"Why did the toilet paper roll down the hill? To get to the BOTTOM!", v:"W"},
  train_will20:{t:"What's a frog's favorite drink? CROAK-a-cola!", v:"W"},
  train_jj1:{t:"What do you call cheese that isn't yours? NACHO cheese!", v:"J"},
  train_jj2:{t:"Why is the banana so popular? Because it's a-PEEL-ing!", v:"J"},
  train_jj3:{t:"What has four wheels and flies? A garbage truck!", v:"J"},
  train_jj4:{t:"Why don't you toot in church? You have to sit in your own PEW!", v:"J"},
  train_jj5:{t:"What's a toilet's favorite game? Hide and POO-seek!", v:"J"},
  train_jj6:{t:"What's brown and sounds like a bell? DUNG!", v:"J"},
  train_jj7:{t:"Why did the poop cross the road? It was on a roll to the potty!", v:"J"},
  train_jj8:{t:"What did one fly ask the other? Is this stool taken?", v:"J"},
  train_jj9:{t:"Why did the math book look sad? It had too many problems!", v:"J"},
  train_jj10:{t:"What do you call a dog magician? A labra-CADABRA-dor!", v:"J"},
  train_jj11:{t:"What did the zero say to the eight? Nice BELT!", v:"J"},
  train_jj12:{t:"What's a ghost's favorite snack? BOO-berries!", v:"J"},
  train_jj13:{t:"Why did the banana wear sunscreen? So it wouldn't PEEL!", v:"J"},
  train_jj14:{t:"What do you call a spider on the computer? A WEB designer!", v:"J"},
  train_jj15:{t:"What's a cat's favorite color? PURR-ple!", v:"J"},
  train_jj16:{t:"Why did the kid bring a ladder to school? For HIGH school!", v:"J"},
  train_jj17:{t:"What animal toots the most? A SMELL-ephant!", v:"J"},
  train_jj18:{t:"What did one wall say to the other? Meet you at the CORNER!", v:"J"},
  train_jj19:{t:"What do you get from a spoiled cow? Rotten milk!", v:"J"},
  train_jj20:{t:"What do you call a fake noodle? An im-PASTA!", v:"J"},
  train_nora1:{t:"You're doing so well, Teddy — I'm cheering for you!", v:"R"},
  train_nora2:{t:"Look how much you've learned. That's amazing!", v:"R"},
  train_nora3:{t:"Take a breath — you've got this. I believe in you!", v:"R"},
  train_nora4:{t:"Wow, you read that beautifully! Keep going!", v:"R"},
  train_nora5:{t:"You're getting smarter every single minute!", v:"R"},
  train_nora6:{t:"I love watching you read, Teddy. You're a star!", v:"R"},
  train_nora7:{t:"One word at a time — you're doing great!", v:"R"},
  train_nora8:{t:"Your brain is a superpower. Go use it!", v:"R"},
  train_nora9:{t:"That one was tricky and you did it anyway. So proud!", v:"R"},
  train_nora10:{t:"Keep it up — you're closer than you think!", v:"R"},
  train_nora11:{t:"You make learning look fun. Let's keep going!", v:"R"},
  train_nora12:{t:"Every try makes you better. You're awesome!", v:"R"},
  train_nora13:{t:"High five, Teddy! That was wonderful reading!", v:"R"},
  train_nora14:{t:"You never give up — that's what makes you a hero!", v:"R"},
  train_nora15:{t:"So close to your goal. You can do it!", v:"R"},
  train_nora16:{t:"Reading is your superpower, and it's getting STRONG!", v:"R"},
  train_nora17:{t:"You're shining today, Teddy. Keep going!", v:"R"},
  train_nora18:{t:"I always knew you were smart. Look at you now!", v:"R"},
  train_nora19:{t:"Little by little, you're becoming a super-reader!", v:"R"},
  train_nora20:{t:"You should be so proud of yourself — because I am!", v:"R"},
  train_cal1:{t:"Why did the kid eat his homework? The teacher said it was a piece of cake!", v:"X"},
  train_cal2:{t:"What do you call a snowman in summer? A puddle!", v:"X"},
  train_cal3:{t:"What's a vampire's favorite fruit? A neck-tarine!", v:"X"},
  train_cal4:{t:"Why did the picture go to jail? Because it was FRAMED!", v:"X"},
  train_cal5:{t:"What do you call a pig that tells jokes? A real HAM!", v:"X"},
  train_cal6:{t:"What did the booger say to the finger? Quit picking on me!", v:"X"},
  train_cal7:{t:"Why are fish so smart? They live in SCHOOLS!", v:"X"},
  train_cal8:{t:"What do you call two birds in love? TWEET-hearts!", v:"X"},
  train_cal9:{t:"What's a skeleton's least favorite room? The LIVING room!", v:"X"},
  train_cal10:{t:"Why did the boy throw butter out the window? To see a butter-FLY!", v:"X"},
  train_cal11:{t:"What's a cow's favorite holiday? MOO Year's Day!", v:"X"},
  train_cal12:{t:"What sound does a nut make when it sneezes? Ca-SHEW!", v:"X"},
  train_cal13:{t:"What did one toot say to the other? You blow me away!", v:"X"},
  train_cal14:{t:"Why did the toilet paper roll to the party? It was a party POOPER!", v:"X"},
  train_cal15:{t:"What's a ghost's favorite ride? The roller-GHOSTER!", v:"X"},
  train_cal16:{t:"What do you call a lazy kangaroo? A pouch potato!", v:"X"},
  train_cal17:{t:"Why can't a leopard hide? It's always SPOTTED!", v:"X"},
  train_cal18:{t:"What do you call a fish wearing a crown? A KING fish!", v:"X"},
  train_cal19:{t:"What sound does a poop make in the pool? Plop-plop!", v:"X"},
  train_cal20:{t:"What's a tornado's favorite game? TWISTER!", v:"X"},
  rest1:{t:"The sun is setting over Star Force City..."},
  rest2:{t:"Even heroes rest. Great work today, Super Teddy. The city is safer because of you!"},
  test:{t:"Hello Super Teddy! This is your mentor speaking. Star Force City needs you!"},
  /* ---- LINE VARIATIONS (anti-fatigue, parent 2026-06-14) — the most-repeated cues rotate via
     varyLine() below. Same meaning + role as the base; sound-ID prompts stay target-INDEPENDENT
     (#4, never name the letter). New ids auto-appear in the Voice Studio for one bulk ReGen; until
     recorded they fall back to TTS, so they're always safe. ---- */
  yes2:{t:"You got it!"}, yes3:{t:"Nice work, hero!"},
  almost2:{t:"So close — listen again..."}, almost3:{t:"Not quite — here it is once more..."},
  find_prompt2:{t:"Listen... which gem makes this sound?"}, find_prompt3:{t:"Use your ears — find the gem that says..."},
  scan_prompt2:{t:"Tap the gem with this sound..."}, scan_prompt3:{t:"Which gem makes this sound? Tap it!"},
  trace_prompt2:{t:"Trace along the glowing stars to free the gem!"}, trace_prompt3:{t:"Follow the stars with your finger to cut it loose!"},
  read_prompt2:{t:"Sound it out... then tap what it means!"}, read_prompt3:{t:"Read the word, then tap its picture!"},
  sent_prompt2:{t:"Read it all... then tap the picture it tells about!"}, sent_prompt3:{t:"Read the whole thing — which picture fits?"},
  train_yes2:{t:"Coin for you!"}, train_yes3:{t:"Ka-ching! Keep it up!"},
  /* ---- BEAT-7 HOMECOMING ENDING (STORY.md §F, parent-APPROVED 2026-06-15). PROCESS praise fused to
     the reading proof. Mom & Dad = the single combined role P (home5/home8, parent's words VERBATIM). ---- */
  home1:{t:"You did it, Sir Teddy. You set the whole kingdom free. Now go home, brave reader — your family is waiting.", v:"N"},
  home2:{t:"In a swirl of light, Super Teddy and his friends tumble home — back to Star Force City, safe and sound."},
  home3:{t:"Look — our hero is home!", v:"L"},
  home4:{t:"Teddy, you read your way through a whole castle of dragons to find me. You sounded out every word, and you never gave up on the hard ones.", v:"K"},
  home5:{t:"Oh Bud! Good boy… I mean good Teddy!", v:"P"},
  home6:{t:"You're ready now, Teddy. Ready for second grade — and you are going to do great.", v:"K"},
  home7:{t:"Your whole team cheers your name — Archie, Ellie, William, Amelia, Leighton, JJ, Nora, and Cal: Super Teddy! Super Teddy!"},
  home8:{t:"Way to go, buddy boy! I'm proud of how hard you worked. You never gave up and you gave it your best, and now look at you… you can actually read! Now let's go play some Minecraft.", v:"P"}
};
/* High-frequency lines that ROTATE to fight repetition fatigue (parent 2026-06-14): base id -> its
   variant pool (incl. the base). varyLine() (called by Aud.play) returns a fresh one != the last
   played; any id with no pool passes through unchanged. Same meaning + role; a missing variant clip
   falls back to TTS, so it's always safe; sound-ID prompts stay target-independent (#4). */
const LINE_VARIANTS={
  yes:["yes","yes2","yes3"], almost:["almost","almost2","almost3"],
  find_prompt:["find_prompt","find_prompt2","find_prompt3"],
  scan_prompt:["scan_prompt","scan_prompt2","scan_prompt3"],
  trace_prompt:["trace_prompt","trace_prompt2","trace_prompt3"],
  read_prompt:["read_prompt","read_prompt2","read_prompt3"],
  sent_prompt:["sent_prompt","sent_prompt2","sent_prompt3"],
  train_yes:["train_yes","train_yes2","train_yes3"]
};
let __lastVar={};
function varyLine(id){ const pool=LINE_VARIANTS[id]; if(!pool||pool.length<2)return id;
  let pick=pool[Math.floor(Math.random()*pool.length)], guard=0;
  while(pool.length>2 && pick===__lastVar[id] && guard++<8) pick=pool[Math.floor(Math.random()*pool.length)];
  __lastVar[id]=pick; return pick; }
