/* =========================================================
   DATA — voice-line manifest (LINES). Pure data, no game-state deps.
   Loaded BEFORE game.js (classic scripts share the top-level scope).
   {t: TTS text, r: rate, v: voice role}. New ids appear in the Voice
   Studio automatically. First slice of the no-build modular split.
========================================================= */
const LINES={
  /* letter sounds — override these with your own recordings for perfect phonics */
  snd_s:{t:"sss",r:.7}, snd_a:{t:"ahh",r:.7}, snd_t:{t:"tuh",r:.75},
  snd_p:{t:"puh",r:.75}, snd_i:{t:"ih",r:.7}, snd_n:{t:"nnn",r:.7},
  snd_m:{t:"mmm",r:.7}, snd_d:{t:"duh",r:.75}, snd_g:{t:"guh",r:.75},
  snd_o:{t:"o",r:.7}, snd_c:{t:"kuh",r:.75}, snd_k:{t:"kuh",r:.75},
  snd_e:{t:"eh",r:.7}, snd_u:{t:"uh",r:.7}, snd_r:{t:"rrr",r:.7},
  snd_h:{t:"hh",r:.7}, snd_b:{t:"buh",r:.75}, snd_f:{t:"fff",r:.7},
  snd_l:{t:"lll",r:.7}, snd_j:{t:"juh",r:.75}, snd_v:{t:"vvv",r:.7}, snd_w:{t:"wuh",r:.75},
  snd_x:{t:"ks",r:.75}, snd_y:{t:"yuh",r:.75}, snd_z:{t:"zzz",r:.7}, snd_q:{t:"kwuh",r:.75},
  like_s:{t:"Like sun!"}, like_a:{t:"Like apple!"}, like_t:{t:"Like tiger!"},
  like_p:{t:"Like pig!"}, like_i:{t:"Like insect!"}, like_n:{t:"Like nest!"},
  like_m:{t:"Like monkey!"}, like_d:{t:"Like dog!"}, like_g:{t:"Like goat!"},
  like_o:{t:"Like octopus!"}, like_c:{t:"Like cat!"}, like_k:{t:"Like kite!"},
  like_e:{t:"Like egg!"}, like_u:{t:"Like umbrella!"}, like_r:{t:"Like rocket!"},
  like_h:{t:"Like hat!"}, like_b:{t:"Like ball!"}, like_f:{t:"Like fish!"},
  like_l:{t:"Like lion!"}, like_j:{t:"Like jar!"}, like_v:{t:"Like van!"}, like_w:{t:"Like web!"},
  like_x:{t:"Like fox!"}, like_y:{t:"Like yo-yo!"}, like_z:{t:"Like zebra!"}, like_q:{t:"Like queen!"},
  intro_s:{t:"Mission! A Vexbot trapped the Letter Gem S! This is S. It says..."},
  intro_a:{t:"Mission! A Vexbot trapped the Letter Gem A! This is A. It says..."},
  intro_t:{t:"Mission! A Vexbot trapped the Letter Gem T! This is T. It says..."},
  intro_p:{t:"Mission! A Vexbot trapped the Letter Gem P! This is P. It says..."},
  intro_i:{t:"Mission! A Vexbot trapped the Letter Gem I! This is I. It says..."},
  intro_n:{t:"Mission! A Vexbot trapped the Letter Gem N! This is N. It says..."},
  intro_m:{t:"Mission! A Vexbot trapped the Letter Gem M! This is M. It says..."},
  intro_d:{t:"Mission! A Vexbot trapped the Letter Gem D! This is D. It says..."},
  intro_g:{t:"Mission! A Vexbot trapped the Letter Gem G! This is G. It says..."},
  intro_o:{t:"Mission! A Vexbot trapped the Letter Gem O! This is O. It says..."},
  intro_c:{t:"Mission! A Vexbot trapped the Letter Gem C! This is C. It says..."},
  intro_k:{t:"Mission! A Vexbot trapped the Letter Gem K! This is K. It says..."},
  intro_e:{t:"Mission! A Vexbot trapped the Letter Gem E! This is E. It says..."},
  intro_u:{t:"Mission! A Vexbot trapped the Letter Gem U! This is U. It says..."},
  intro_r:{t:"Mission! A Vexbot trapped the Letter Gem R! This is R. It says..."},
  intro_h:{t:"Mission! A Vexbot trapped the Letter Gem H! This is H. It says..."},
  intro_b:{t:"Mission! A Vexbot trapped the Letter Gem B! This is B. It says..."},
  intro_f:{t:"Mission! A Vexbot trapped the Letter Gem F! This is F. It says..."},
  intro_l:{t:"Mission! A Vexbot trapped the Letter Gem L! This is L. It says..."},
  intro_j:{t:"Mission! A Vexbot trapped the Letter Gem J! This is J. It says..."},
  intro_v:{t:"Mission! A Vexbot trapped the Letter Gem V! This is V. It says..."},
  intro_w:{t:"Mission! A Vexbot trapped the Letter Gem W! This is W. It says..."},
  intro_x:{t:"Mission! A Vexbot trapped the Letter Gem X! This is X. It says..."},
  intro_y:{t:"Mission! A Vexbot trapped the Letter Gem Y! This is Y. It says..."},
  intro_z:{t:"Mission! A Vexbot trapped the Letter Gem Z! This is Z. It says..."},
  intro_q:{t:"Mission! A Vexbot trapped the Letter Gem Q! This is Q. It says..."},
  /* --- ACT 2: digraph sounds, keywords, intros, words (one gem = one sound) --- */
  snd_sh:{t:"sh",r:.6}, snd_ch:{t:"ch",r:.7}, snd_th:{t:"th",r:.6}, snd_wh:{t:"wh",r:.6}, snd_ck:{t:"k",r:.75}, snd_ng:{t:"ng",r:.6},
  like_sh:{t:"Like ship!"}, like_ch:{t:"Like cheese!"}, like_th:{t:"Like thumb!"}, like_wh:{t:"Like whale!"}, like_ck:{t:"Like duck!"}, like_ng:{t:"Like ring!"},
  /* VOWEL TEAMS (ai/ee/oa) — one long-vowel sound; phonemes the parent can record (snd_ prefix) */
  snd_ai:{t:"ay",r:.7}, snd_ee:{t:"ee",r:.7}, snd_oa:{t:"oh",r:.7},
  intro_ai:{t:"This is the A-I team! Two vowels — the A does the talking and says its name."}, like_ai:{t:"Like rain!"},
  intro_ee:{t:"This is the E-E team! It says the long E — eee."}, like_ee:{t:"Like bee!"},
  intro_oa:{t:"This is the O-A team! The O does the talking and says its name."}, like_oa:{t:"Like boat!"},
  word_rain:{t:"rain!"}, word_train:{t:"train!"}, word_sail:{t:"sail!"}, word_feet:{t:"feet!"}, word_bee:{t:"bee!"}, word_tree:{t:"tree!"}, word_seed:{t:"seed!"},
  word_boat:{t:"boat!"}, word_coat:{t:"coat!"}, word_goat:{t:"goat!"}, word_soap:{t:"soap!"}, word_road:{t:"road!"}, word_leaf:{t:"leaf!"},
  intro_sh:{t:"New rune, brave knight! S and H join to make ONE sound... sh! Like ship."},
  intro_ch:{t:"New rune! C and H together say... ch! Like cheese."},
  intro_th:{t:"New rune! T and H together say... th! Like thumb."},
  intro_wh:{t:"New rune! W and H together say... wh! Like whale."},
  intro_ck:{t:"New rune! C and K at the end of a word say... k! Like duck."},
  intro_ng:{t:"New rune! N and G together say... ng! Like ring."},
  word_ship:{t:"ship!"}, word_chat:{t:"chat!"}, word_this:{t:"this!"}, word_duck:{t:"duck!"}, word_sock:{t:"sock!"},
  word_ring:{t:"ring!"}, word_king:{t:"king!"}, word_fish:{t:"fish!"}, word_chip:{t:"chip!"}, word_shop:{t:"shop!"},
  word_chin:{t:"chin!"}, word_bath:{t:"bath!"}, word_wing:{t:"wing!"}, word_dish:{t:"dish!"},
  /* Act-2 zone 2 — BLEND words */
  word_stop:{t:"stop!"}, word_frog:{t:"frog!"}, word_clap:{t:"clap!"}, word_swim:{t:"swim!"}, word_snap:{t:"snap!"},
  word_glad:{t:"glad!"}, word_plum:{t:"plum!"}, word_hand:{t:"hand!"}, word_jump:{t:"jump!"}, word_milk:{t:"milk!"},
  word_nest:{t:"nest!"}, word_sled:{t:"sled!"}, word_gift:{t:"gift!"}, word_trap:{t:"trap!"}, word_belt:{t:"belt!"},
  word_drum:{t:"drum!"}, word_flag:{t:"flag!"}, word_crab:{t:"crab!"}, word_star:{t:"star!"}, word_lamp:{t:"lamp!"},
  word_tent:{t:"tent!"}, word_mask:{t:"mask!"}, word_stomp:{t:"stomp!"}, word_blend:{t:"blend!"}, word_crust:{t:"crust!"}, word_drink:{t:"drink!"},
  blend_intro:{t:"To the Iron Forge, Sir Teddy! Here we BLEND sounds — two letters, side by side, said quickly together. Listen, then build!"},
  /* Act-2 zone 3 — LONG VOWELS / Magic-E. Long-vowel sounds = the vowel's NAME. */
  snd_a_long:{t:"ay",r:.7}, snd_e_long:{t:"ee",r:.7}, snd_i_long:{t:"eye",r:.7}, snd_o_long:{t:"oh",r:.7}, snd_u_long:{t:"you",r:.7},
  magic_intro:{t:"A new spell, Sir Teddy — the MAGIC E! A short vowel says its little sound... but add a silent E at the end, and the vowel says its NAME!"},
  magic_short:{t:"This word says..."},
  magic_cast:{t:"MAGIC E! The silent E flips the vowel — now it says its name!"},
  magic_done:{t:"Spell mastered! You can hear the long vowel sing. Noah the Red salutes you!"},
  word_cape:{t:"cape!"}, word_tape:{t:"tape!"}, word_kit:{t:"kit!"}, word_kite:{t:"kite!"}, word_pine:{t:"pine!"},
  word_hope:{t:"hope!"}, word_not:{t:"not!"}, word_note:{t:"note!"}, word_cub:{t:"cub!"}, word_cube:{t:"cube!"},
  word_tub:{t:"tub!"}, word_tube:{t:"tube!"}, word_cake:{t:"cake!"}, word_time:{t:"time!"}, word_home:{t:"home!"},
  word_rope:{t:"rope!"}, word_bike:{t:"bike!"}, word_gate:{t:"gate!"}, word_nose:{t:"nose!"}, word_rose:{t:"rose!"}, word_cute:{t:"cute!"},
  /* Noah the Red — Act-2 mentor intro */
  noah1:{t:"Greetings, young hero. I am Noah the Red, wizard of the old realm. The Vixen has dragged your friends here, to the age of knights and dragons."},
  noah2:{t:"Your gem-powers are gone — but together we will earn new magic: RUNES. Two letters that join to make ONE sound. Master them, and the dragons cannot stand against you."},
  noah3:{t:"Welcome to Stonekeep Village, Sir Teddy. Your first runes await. Onward!"},
  act2_win:{t:"A dragon falls! Your runes grow stronger, Sir Teddy. Noah the Red is proud."},
  word_at:{t:"at!"}, word_sat:{t:"sat!"}, word_tap:{t:"tap!"}, word_pin:{t:"pin!"}, word_nap:{t:"nap!"},
  word_dad:{t:"dad!"}, word_mad:{t:"mad!"}, word_dig:{t:"dig!"},
  word_cat:{t:"cat!"}, word_dog:{t:"dog!"}, word_mom:{t:"mom!"}, word_kid:{t:"kid!"},
  word_red:{t:"red!"}, word_run:{t:"run!"}, word_rug:{t:"rug!"}, word_rub:{t:"rub!"},
  word_fun:{t:"fun!"}, word_hen:{t:"hen!"}, word_bed:{t:"bed!"}, word_bug:{t:"bug!"},
  word_sun:{t:"sun!"}, word_pig:{t:"pig!"}, word_hat:{t:"hat!"}, word_cup:{t:"cup!"}, word_bus:{t:"bus!"},
  word_bag:{t:"bag!"}, word_cap:{t:"cap!"}, word_pan:{t:"pan!"}, word_nut:{t:"nut!"}, word_fan:{t:"fan!"},
  word_mug:{t:"mug!"}, word_pot:{t:"pot!"}, word_hug:{t:"hug!"}, word_net:{t:"net!"}, word_bun:{t:"bun!"},
  word_let:{t:"let!"}, word_jam:{t:"jam!"}, word_van:{t:"van!"}, word_box:{t:"box!"}, word_fox:{t:"fox!"}, word_zip:{t:"zip!"}, word_wax:{t:"wax!"},
  word_hop:{t:"hop!"}, word_wet:{t:"wet!"},
  cloze_intro:{t:"READING DOJO! Read the whole sentence, then tap the word that fits the blank!"},
  cloze_prompt:{t:"Which word fits? Read it and tap!"},
  scram_intro:{t:"Sentence building! Listen to the sentence, then tap the words in the right order!"},
  scram_prompt:{t:"Build the sentence! Tap the words in order."},
  dojo_yes:{t:"Perfect reading, Super Teddy!"},
  gear_fluency:{t:"The FLUENCY BADGE! You read like a real reader now!"},
  m4_letters:{t:"You rescued ALL the Letter Gems! Every letter in Star Force City is FREE! Now... the road to reading, and to Lord Vex's Fortress!"},
  read_intro:{t:"READING RALLY! Now YOU read the words, hero. Sound them out, then tap the picture it means!"},
  read_prompt:{t:"Read the word... then tap what it means!"},
  read_yes:{t:"You READ it! Awesome!"},
  rally_champ:{t:"You are a READING CHAMPION, Super Teddy! You can read real words now!"},
  gear_crown:{t:"The READING CROWN! Only true readers can wear it!"},
  gear_alphabet:{t:"The ALPHABET STAR! All 26 Letter Gems, rescued by you!"},
  sw_I:{t:"I"}, sw_a:{t:"a"}, sw_the:{t:"the"}, sw_to:{t:"to"}, sw_and:{t:"and"},
  sw_is:{t:"is"}, sw_you:{t:"you"}, sw_said:{t:"said"},
  spell_intro:{t:"HEART WORDS! Most of each word you CAN sound out — only the heart letter is tricky, so we just remember that one bit."},
  spell_new:{t:"Let's map the sounds. This word says..."},
  spell_build:{t:"Build the word you hear — sound by sound!"},
  spell_heart:{t:"Heart letter! This one's tricky — we just remember it."},
  spell_prompt:{t:"Cast the Instant Spell that says..."},
  spell_yes:{t:"Spell built! You mapped the sounds!"},
  spell_done:{t:"You are a MASTER SPELL CASTER, Super Teddy! Heart words: mastered!"},
  gear_tome:{t:"The SPELL TOME! It holds every heart word you know!"},
  word_ran:{t:"ran!"}, word_hot:{t:"hot!"}, word_big:{t:"big!"}, word_can:{t:"can!"}, word_had:{t:"had!"},
  sent_intro:{t:"THE STORY GATE! This is real reading, hero. Tap each word to read it, then tap the picture the sentence tells about!"},
  sent_prompt:{t:"Read the whole sentence... then tap the picture it tells about!"},
  sent_yes:{t:"YES! You READ a whole sentence, Super Teddy!"},
  sent_champ:{t:"You did it! You can READ, Super Teddy! Real sentences! The Story Gate is OPEN — Lord Vex's Fortress is next!"},
  gear_storykey:{t:"The STORY KEY! It unlocks every story in Star Force City!"},
  panel1:{t:"This is Star Force City. A city powered by magical Letter Gems, words, and stories."},
  panel2:{t:"But one night, LORD VEX and his Vexbot army attacked! They stole the Letter Gems and smashed every word into pieces. Now nobody can read. Not signs, not books, not even bedtime stories."},
  panel3:{t:"The city needed a hero. The founders of the Hero League, your mom and dad, searched everywhere... and they chose YOU, Super Teddy."},
  panel4:{t:"These are the Gem Lenses. Your glasses are superpowered! With them, you can see hidden Letter Gems nobody else can see."},
  panel5:{t:"Rescue the gems. Rebuild the words. Save Star Force City! Are you ready, Super Teddy?"},
  welcome:{t:"Welcome back, Super Teddy!"},
  locked_tip:{t:"Not yet, hero! Finish the missions on the path first — then this one unlocks."},
  pick:{t:"Pick your mission, Super Teddy!"},
  scan_intro:{t:"Lens calibration! Let's charge your Gem Lenses. There are no wrong answers. Every tap makes them stronger!"},
  scan_prompt:{t:"Tap the gem that says..."},
  scan_done:{t:"Lenses fully charged! Time for your first mission, hero!"},
  trace_prompt:{t:"Trace the gem to cut it free! Follow the glowing stars with your finger."},
  freed:{t:"You cut the gem free!"},
  find_prompt:{t:"Find the gem that says..."},
  yes:{t:"Yes!"},
  almost:{t:"Almost! Listen again..."},
  boss_intro:{t:"A VEXBOT is attacking! Blast it! Tap the gem that says..."},
  hit_again:{t:"Direct hit! Again!"},
  dodge:{t:"He dodged! Listen..."},
  flee:{t:"SYSTEM FAILURE! VEXBOT RETREATING!", v:"C"},
  youdidit:{t:"You did it, Super Teddy!"},
  /* ---- villain BATTLE taunts (intro monologue) + DEFEAT lines ("I'll get you next time") ---- */
  boss_taunt:{t:"You again, Super Teddy? Hand over those Letter Gems and nobody gets zapped!", v:"C"},
  boss_flee:{t:"This isn't over, hero! I'll be back for those gems!", v:"C"},
  vex_taunt:{t:"So... you reached my fortress. Foolish child. You will NEVER read your way past LORD VEX!", v:"C"},
  vex_defeat:{t:"Impossible! Beaten by a child who learned to READ?! I'll get you next time, Super Teddy!", v:"C"},
  vixen_taunt:{t:"Welcome to my Dragon Keep, little knight. Miss Kendall belongs to ME now. Turn back while you can!", v:"V"},
  vixen_defeat:{t:"NO! My beautiful dragon! You have NOT seen the last of me, Sir Teddy. I'll get you next time!", v:"V"},
  patrol_intro:{t:"Rooftop patrol! Letter Gems are hiding all over the city. Find them, hero!"},
  mastery_review:{t:"So close, hero! A few Letter Gems need more power before this rescue. Quick patrol to lock them in!"},
  cue_b:{t:"Watch out, hero! b and d are mirror twins. b has its round belly in FRONT, after the tall line. Listen: buh — like ball!"},
  cue_d:{t:"Careful! d and b are mirror twins. d has its round belly FIRST, before the tall line. Listen: duh — like dog!"},
  cue_p:{t:"Watch out! p and q are mirror twins. p has its round belly in FRONT. Listen: puh — like pig!"},
  cue_q:{t:"Careful! q and p are mirror twins. q has its round belly FIRST, with a tail. Listen: kwuh — like queen!"},
  cue_n:{t:"Careful! n and m are alike. n has ONE bump. Listen: nnn — like nest!"},
  cue_m:{t:"Watch out! m and n are alike. m has TWO bumps. Listen: mmm — like monkey!"},
  cue_u:{t:"Careful! u and n are flips. u is a cup, open at the TOP. Listen: uh — like umbrella!"},
  cue_w:{t:"Watch out! w and m are flips. w points UP like two valleys. Listen: wuh — like web!"},
  daily_goal:{t:"Daily training complete! You trained like a true champion today, Super Teddy!"},
  forge_intro1:{t:"The WORD FORGE is open!"},
  forge_intro2:{t:"Gems together make WORDS. And words forge the mightiest weapons!"},
  forge_build:{t:"Build the word! Listen..."},
  forge_next:{t:"Next sound..."},
  forge_listen:{t:"Listen for the next sound..."},
  blast:{t:"BLAST!"},
  forge_win1:{t:"The Vexbot is DESTROYED!"},
  forge_win2:{t:"You READ words, Super Teddy! You are a true hero!"},
  win_grow:{t:"Gem rescued! Your power grows, Super Teddy! Look at those muscles!"},
  win_gear:{t:"You earned new gear!"},
  gear_belt:{t:"The Power Belt!"}, gear_boots:{t:"Rocket Boots!"}, gear_shield:{t:"The GEM SHIELD! Forged from power words!"}, gear_gauntlet:{t:"The GEM GAUNTLET! Now your word power is unstoppable!"},
  m3_done:{t:"You crushed the Vex Captain and conquered Thunder Ridge! Lord Vex's Fortress is just ahead, Super Teddy..."},
  gear_hammer:{t:"The WORD HAMMER! Forged from your first words!"}, gear_sword:{t:"The GEM SWORD! A true hero's blade!"}, base1:{t:"Welcome to your Hero Base, Super Teddy! Gear up and look strong!"},
  train_intro:{t:"Training Room! Build and read words to earn coins, Super Teddy. Practice makes you POWERFUL!"},
  train_build:{t:"Build the word you hear!"},
  train_read:{t:"Read the word, then tap what it means!"},
  train_yes:{t:"Coin earned!"},
  train_none:{t:"Learn a few letters on the missions first, then come back to train!"},
  shop_need:{t:"Not enough coins yet — train a little more, hero!"},
  finale1:{t:"Incoming message! ... Super Teddy! It's Amelia!", v:"B"},
  finale2:{t:"Lord Vex trapped me in the Heart Tower! Come rescue me in your next adventure!", v:"B"},
  finale3:{t:"To be continued, hero..."},
  fort_intro:{t:"THIS IS IT, Super Teddy! Lord Vex's Fortress! Leighton is locked inside. Use EVERYTHING you've learned — bring him down!"},
  fort_t1:{t:"FOOLISH HERO! My gem shield is UNBREAKABLE!", v:"C"},
  fort_t2:{t:"You cannot read my word-locks! NOBODY can!", v:"C"},
  fort_t3:{t:"Impossible! How do you know these spells?!", v:"C"},
  fort_t4:{t:"NO! Not the sentences! My power is FADING!", v:"C"},
  fort_p1:{t:"PHASE ONE — blast the GEM SHIELD! Tap the gem that makes the sound…"},
  fort_p2:{t:"PHASE TWO — smash the WORD-LOCKS! Read each word, tap what it means!"},
  fort_p3:{t:"PHASE THREE — cast your INSTANT SPELLS! Tap the word you hear!"},
  fort_p4:{t:"FINAL PHASE — READ to free Leighton! Read each sentence and answer it!"},
  fort_hit:{t:"DIRECT HIT!"},
  fort_win1:{t:"VEX'S ARMOR SHATTERS! SYSTEM FAILURE!", v:"C"},
  leighton1:{t:"You did it, Super Teddy! You READ your way to victory! Lord Vex is defeated!"},
  leighton2:{t:"Super Teddy! You found me! I always knew you could read! You're my hero!", v:"B"},
  leighton3:{t:"LEIGHTON, the Starlight Princess, is FREE! Star Force City is SAVED! The main story is complete — you are a true READER and a true HERO!"},
  interlude1:{t:"Wait, Super Teddy — an urgent message is coming in! It's your Mom and Dad!"},
  interlude2:{t:"Hero, we are SO proud of you. But there's no time to rest. A cunning new villain has appeared — and she has kidnapped Miss Kendall... and your friends JJ, Nora, and Cal!"},
  interlude3:{t:"Hello, little hero. Such a shame to spoil your party. I'm whisking your precious friends far, far away — to a time long, long ago. Do try to catch up... if you can. Ta-ta!", v:"V"},
  interlude4:{t:"She slipped through a shimmering time portal — to the age of KNIGHTS and DRAGONS! A mighty wizard named Noah the Red is already there, waiting to help you, hero."},
  interlude_knight:{t:"You leap into the portal! In a swirl of light your gems and gear are gone... and you rise again as SUPER TEDDY THE KNIGHT! A brave new quest awaits."},
  interlude5:{t:"Rest now, champion. Your medieval adventure is being built, and begins very soon. TO BE CONTINUED!"},
  /* ===== ACT-2 FINALE — Dragon Keep / rescue Miss Kendall ===== */
  f2_intro:{t:"THE DRAGON KEEP, Sir Teddy! The Vixen has Miss Kendall locked in the highest tower, guarded by her mightiest dragon. Use your RUNES, your BLENDS, and your MAGIC-E — bring it down!"},
  f2_p1:{t:"Break the dragon ward! Tap the gem that makes the sound…"},
  f2_p2:{t:"Shatter the rune-locks! Read the word, then tap what it means!"},
  f2_p3:{t:"Cast your spells! Build the word you hear — sound by sound!"},
  f2_p4:{t:"FINAL STAND — read to free Miss Kendall! Read the word and tap what it means!"},
  f2_t1:{t:"You shall not pass, little knight!", v:"V"},
  f2_t2:{t:"My runes will hold forever!", v:"V"},
  f2_t3:{t:"Magic? You call THAT magic?", v:"V"},
  f2_t4:{t:"No! My dragon — it falls!", v:"V"},
  f2_win:{t:"The dragon is defeated! The Vixen flees in a swirl of smoke!"},
  kendall1:{t:"You did it, Sir Teddy! You READ your way through the whole Dragon Keep!"},
  kendall2:{t:"Teddy! My brave knight — you came for me! I always knew you would learn to read. Thank you, hero!"},
  kendall3:{t:"MISS KENDALL is FREE! The medieval realm is safe, and you are a TRUE READER and a TRUE KNIGHT. What a champion!"},
  free_tank:{t:"CAGE DESTROYED! You freed Archie! TANK has joined the Hero League... and he is ready to SMASH!"},
  free_flip:{t:"CAGE DESTROYED! You freed Ellie! FLIP has joined the league... backflips, cartwheels, and mid-air gem grabs!"},
  free_sunny:{t:"CAGE DESTROYED! You freed William! SUNNY has joined the league... and things are about to get silly!"},
  free_heart1:{t:"TOWER UNLOCKED! You read your way to the top of Heart Tower!"},
  free_heart2:{t:"Super Teddy! You saved me! I KNEW you could read those words! Heartguard is on the team, little hero!", v:"B"},
  m2_done:{t:"HEARTGUARD has joined the Hero League! Lord Vex is furious... and Star Force City shines brighter than ever!"},
  heart_cheer1:{t:"Amazing reading, Super Teddy!", v:"B"},
  heart_cheer2:{t:"That's my little brother, everyone!", v:"B"},
  heart_cheer3:{t:"Heartguard is SO proud of you!", v:"B"},
  cheer_archie1:{t:"BOOM! Smash that Vexbot, Super Teddy! Archie's got your back!", v:"T"},
  cheer_archie2:{t:"So strong, Super Teddy! That's how Archie does it! Hit it again!", v:"T"},
  cheer_ellie1:{t:"Beautiful, Super Teddy! Ellie says you stuck the landing!", v:"F"},
  cheer_ellie2:{t:"Woo! Super neat tracing! Ellie's doing a cartwheel for you!", v:"F"},
  cheer_will1:{t:"Wheee! William found it! Wait... YOU found it! Hooray!", v:"W"},
  cheer_will2:{t:"Sparkles everywhere! Awesome finding, Super Teddy! Says William!", v:"W"},
  rest1:{t:"The sun is setting over Star Force City..."},
  rest2:{t:"Even heroes rest. Great work today, Super Teddy. The city is safer because of you!"},
  test:{t:"Hello Super Teddy! This is your mentor speaking. Star Force City needs you!"}
};
